config/routes.rb
TestSite::Application.routes.draw do
  resources :posts

  get '/all', :to => 'posts#index', :as => 'all'
end

app/models/post.rb
class Post < ActiveRecord::Base

  # Counter-intutive that this line would prevent the saving of
  # Post attributes
  # attr_accessor :artist, :song, :body, :album, :artist, :release_date, :notes, :radio_station, :dj_name, :spun_at, :radio_station_url, :music_director, :created_at, :updated_at

  # def new
  #   @artist = "foo"
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post]
    if @post.save
      redirect_to posts_path
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes params[:post]
      redirect_to posts_path
    else
      render :action => :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestSite</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
  <%= form.text_field :title %></br>
  <%= "Title #{@post.errors[:title]}" if @post.errors[:title] %></br>
  <%= form.text_area :body %></br>
  <%= form.submit %>
<% end -%>

app/views/posts/edit.html.erb
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<h1>List of posts</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post %></td>
      <td>
        <%= link_to 'Edit', edit_post_path(post.id) %>
        <%= link_to 'Delete', post, :method => 'delete' %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Post', new_post_path %></p>

app/views/posts/new.html.erb
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.body %>

<a href="/posts/<%= @post.id %>/edit">Edit</a>